import * as T from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {EffectComposer} from 'three/addons/postprocessing/EffectComposer.js';
import {RenderPass} from 'three/addons/postprocessing/RenderPass.js';
import {SSAOPass} from 'three/addons/postprocessing/SSAOPass.js';
import {RoomEnvironment} from 'three/addons/environments/RoomEnvironment.js';
import {SMAAPass} from 'three/addons/postprocessing/SMAAPass.js';
import {OutputPass} from 'three/addons/postprocessing/OutputPass.js';
import {waterState} from './model/water.mjs';
const stage=document.querySelector('#stage'),status=document.querySelector('#status'),renderer=new T.WebGLRenderer({antialias:true,preserveDrawingBuffer:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.15;stage.prepend(renderer.domElement);
const scene=new T.Scene();const pmrem=new T.PMREMGenerator(renderer);const envScene=new RoomEnvironment();scene.environment=pmrem.fromScene(envScene,.04).texture;envScene.dispose();pmrem.dispose();scene.environmentIntensity=.22;scene.background=new T.Color('#151710');const camera=new T.PerspectiveCamera(42,1,.08,80);const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.maxDistance=23;controls.minDistance=.7;controls.maxPolarAngle=Math.PI*.92;
const ambient=new T.HemisphereLight(0xc0c9cb,0x32251a,.75);scene.add(ambient);
const key=new T.DirectionalLight(0xffe3b7,2.6);key.position.set(-2,7,-4);key.castShadow=true;key.shadow.mapSize.set(2048,2048);Object.assign(key.shadow.camera,{left:-6,right:6,top:6,bottom:-6,near:.1,far:25});key.shadow.bias=-.0003;key.shadow.normalBias=.025;scene.add(key);
const fill=new T.PointLight(0xbec8d4,6,15,2);fill.position.set(2,3,-3);scene.add(fill);
const bounce=new T.PointLight(0xe6c391,14,13,2);bounce.position.set(-1,2.5,2.2);scene.add(bounce);
const composer=new EffectComposer(renderer);composer.addPass(new RenderPass(scene,camera));const ao=new SSAOPass(scene,camera,800,600);ao.kernelRadius=.16;ao.minDistance=.002;ao.maxDistance=.10;composer.addPass(ao);composer.addPass(new OutputPass());composer.addPass(new SMAAPass());
let room,drips=[],view='inside';const poses={web:{p:[-.4,2.1,.7],t:[-2.9,2.65,2.8],f:48},shoulder:{p:[-1,1.8,-2],t:[2.45,1.7,-.25],f:58},entry:{p:[.7,1.6,-3.6],t:[2.9,.3,-.8],f:70},overview:{p:[.6,5.3,-10.5],t:[0,1.3,.25],f:42},inside:{p:[0,1.7,-2.95],t:[-.25,1.8,2.5],f:78},rubble:{p:[2.65,1.15,-3.7],t:[2.5,.24,-1.9],f:65},rock:{p:[-1.5,2.9,-4.5],t:[2.3,1.6,.05],f:65},top:{p:[0,18,-.001],t:[0,0,0],f:40},alcove:{p:[2.6,.75,-1.6],t:[3,.25,-.7],f:65},pool:{p:[-.3,2.6,-4],t:[-2.45,1.8,-2.3],f:70}};
function visibility(){if(!room)return;room.getObjectByName('ceiling').visible=document.querySelector('#roof').checked;room.getObjectByName('south').visible=document.querySelector('#front').checked;room.getObjectByName('ceilingTips').visible=view!=='top';room.getObjectByName('roofRim').visible=view!=='top';}
function pose(name){view=name;document.querySelector('#front').checked=name==='top'||name==='inside'||name==='entry';document.querySelector('#roof').checked=name==='inside'||name==='entry'||name==='web';fill.intensity=name==='inside'?18:6;const p=poses[name];controls.enableDamping=false;controls.update();camera.position.set(...p.p);camera.up.set(0,1,0);controls.target.set(...p.t);camera.fov=p.f;camera.updateProjectionMatrix();controls.update();controls.enableDamping=true;document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===name));visibility();if(room)composer.render();}
for(const b of document.querySelectorAll('[data-view]'))b.onclick=()=>pose(b.dataset.view);for(const id of ['roof','front'])document.querySelector('#'+id).onchange=visibility;
document.querySelector('#light').oninput=e=>{renderer.toneMappingExposure=Number(e.target.value);};document.querySelector('#ref').onclick=()=>document.querySelector('#reference').showModal();document.querySelector('#close').onclick=()=>document.querySelector('#reference').close();
new GLTFLoader().register(parser=>{parser.textureLoader=new T.TextureLoader(parser.options.manager);return {name:'StableTextureDecode'};}).load('/models/straight-wet-karst-closed-walls.glb?v=27-closed',g=>{room=g.scene;room.scale.x=-1;room.updateMatrix();scene.add(room);room.traverse(o=>{if(o.isMesh){o.castShadow=!['water','webs'].includes(o.name);o.receiveShadow=o.name!=='webs';if(o.name==='webs'){o.material.depthWrite=false;o.renderOrder=2;}if(o.name==='water')o.material.envMapIntensity=.08;for(const mat of (Array.isArray(o.material)?o.material:[o.material]))if(mat.map)mat.map.anisotropy=Math.min(8,renderer.capabilities.getMaxAnisotropy());}});const meta=room.getObjectByName('straight_wet_karst').userData;
for(const d of meta.drips){const drop=new T.Mesh(new T.SphereGeometry(.017,6,8),new T.MeshStandardMaterial({color:0xd0d7ce,roughness:.1,metalness:.1,transparent:true,opacity:.8}));drop.scale.y=2.2;scene.add(drop);const rings=[];for(let i=0;i<3;i++){const r=new T.Mesh(new T.RingGeometry(.94,1,48),new T.MeshBasicMaterial({color:0x9dafa2,transparent:true,opacity:.25,depthWrite:false,side:T.DoubleSide}));r.rotation.x=-Math.PI/2;r.position.set(-d.end[0],d.end[1]+.006,d.end[2]);scene.add(r);rings.push(r);}drips.push({d,drop,rings});}pose(view);status.textContent=`R27 · 封墙审阅 · 模型已就绪 · ${meta.roomIdentity.roomId} · 拖拽可自由观察`;},undefined,()=>{status.textContent='载入失败，请刷新重试';});
function resize(){const w=stage.clientWidth,h=stage.clientHeight;renderer.setSize(w,h);composer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix();}new ResizeObserver(resize).observe(stage);pose(view);resize();
let last=0;renderer.setAnimationLoop(ms=>{if(document.hidden||ms-last<32)return;last=ms;controls.update();const water=room?.getObjectByName('water');if(water?.material.normalMap){water.material.normalMap.offset.set(ms*.000005,ms*.000003);}for(const {d,drop,rings}of drips){const s=waterState(d,ms/1000);drop.position.set(-d.start[0],s.y,d.start[2]);drop.visible=s.falling&&view!=='top';for(let i=0;i<rings.length;i++){const age=s.rippleAge-i*.11;const radius=.02+Math.max(0,age)*.38;rings[i].scale.setScalar(radius);rings[i].material.opacity=age>=0&&age<.7?.25*(1-age/.7):0;}}composer.render();});
window.addEventListener('pagehide',()=>{renderer.setAnimationLoop(null);controls.dispose();composer.dispose();scene.traverse(o=>{o.geometry?.dispose();if(o.material){for(const m of Array.isArray(o.material)?o.material:[o.material]){for(const v of Object.values(m))if(v?.isTexture)v.dispose();m.dispose();}}});scene.environment?.dispose();renderer.dispose();});
