using System;using System.IO;using System.Linq;using System.Text.Json;using System.Text.Json.Nodes;using LethalDungeon.Domain.Dungeons;using LethalDungeon.CatalogJson;using NUnit.Framework;
namespace LethalDungeon.Tests {
 // MAP-037, JSON-004: seeded shared door candidates, strict offsets and rotated geometry.
 public class RandomDoorTests {
 static string Input(){var d=JsonNode.Parse(File.ReadAllText(Path.Combine(TestContext.CurrentContext.TestDirectory,"base-rooms.json")))!;d["schemaVersion"]="room-catalog-v2";foreach(var r in d["rooms"]!.AsArray())foreach(var s in r!["sockets"]!.AsArray())s!["tangentOffsets"]=r["matching"]!["cells"]!.AsArray().Count==1?new JsonArray(-2,0,2):new JsonArray(0);return d.ToJsonString();}
 [Test] public void ConfiguredOffsetsProduceAlignedNoncentralDoors(){var c=RoomCatalogJson.Parse(Input());var g=ConfiguredDungeon.Generate(c,5,100000);Assert.That(g.Layout.Succeeded,Is.True,g.Layout.Failure);var m=g.Layout.Manifest!;Assert.That(LayoutValidator.Validate(c.Geometry,m).IsValid,Is.True);int shifted=0;foreach(var link in m.Connections){var a=m.Rooms.Single(r=>r.InstanceId==link.FromRoom);var b=m.Rooms.Single(r=>r.InstanceId==link.ToRoom);var sa=LayoutGeometry.WorldSocket(c.Geometry.Get(a.ModuleId),a,link.FromSocket);var sb=LayoutGeometry.WorldSocket(c.Geometry.Get(b.ModuleId),b,link.ToSocket);Assert.That(sa.Position,Is.EqualTo(sb.Position));var nominal=c.Geometry.Get(a.ModuleId).Sockets.Single(s=>s.Id==link.FromSocket);var rotated=LayoutGeometry.Rotate(nominal.Position,a.QuarterTurns);if(sa.Position.X!=rotated.X+a.Position.X||sa.Position.Z!=rotated.Z+a.Position.Z)shifted++;}Assert.That(shifted,Is.GreaterThan(0));Assert.That(JsonSerializer.Serialize(g),Is.EqualTo(JsonSerializer.Serialize(ConfiguredDungeon.Generate(c,5,100000))));File.WriteAllText(Path.Combine(TestContext.CurrentContext.TestDirectory,"random-doors.json"),JsonSerializer.Serialize(g,new JsonSerializerOptions{WriteIndented=true}));}
 [TestCase(-7,0,2)] [TestCase(-2,0,0)] [TestCase(-2,1,2)]
 public void InvalidCandidateSetsAreRejected(int a,int b,int c){var d=JsonNode.Parse(Input())!;d["rooms"]![0]!["sockets"]![0]!["tangentOffsets"]=new JsonArray(a,b,c);Assert.Throws<ArgumentException>(new Action(()=>RoomCatalogJson.Parse(d.ToJsonString())));}
 [Test] public void UndeclaredAndUnknownOverridesAreRejected(){var c=RoomCatalogJson.Parse(Input());foreach(var key in new[]{"south","missing"}){var room=new PlacedRoom("a","corner_left",new GridPoint(),0,new System.Collections.Generic.Dictionary<string,int>{{key,3}});Assert.That(LayoutValidator.Validate(c.Geometry,new DungeonManifest(c.Geometry.Version,new[]{room},Array.Empty<DoorConnection>())).Errors.Any(e=>e.StartsWith("InvalidSocketOffset:")),Is.True);}}
 [Test] public void RotationTransformsLocalOffsetWithTheRoom(){var c=RoomCatalogJson.Parse(Input());foreach(var q in Enumerable.Range(0,4)){var r=new PlacedRoom("a","corner_left",new GridPoint(),q,new System.Collections.Generic.Dictionary<string,int>{{"south",2}});Assert.That(LayoutGeometry.WorldSocket(c.Geometry.Get("corner_left"),r,"south").Position,Is.EqualTo(LayoutGeometry.Rotate(new GridPoint(2,0,-8),q)));}}
 }
}
