import {makeCutawayCap} from './cutaway.mjs?revision=39';
import {EffectComposer} from 'three/addons/postprocessing/EffectComposer.js';import {RenderPass} from 'three/addons/postprocessing/RenderPass.js';import {SSAOPass} from 'three/addons/postprocessing/SSAOPass.js';import {OutputPass} from 'three/addons/postprocessing/OutputPass.js';
import * as T from 'three';import {OrbitControls} from 'three/addons/controls/OrbitControls.js';import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';import {RoomEnvironment} from 'three/addons/environments/RoomEnvironment.js';
const scene=new T.Scene();scene.background=new T.Color(0x10120f);const renderer=new T.WebGLRenderer({antialias:true,preserveDrawingBuffer:true});renderer.localClippingEnabled=true;renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.setSize(innerWidth,innerHeight);renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.0;document.body.append(renderer.domElement);let camera=new T.PerspectiveCamera(76,innerWidth/innerHeight,.03,100);const perspectiveCamera=camera,planCamera=new T.OrthographicCamera(-5.2*innerWidth/innerHeight,5.2*innerWidth/innerHeight,5.2,-5.2,.03,100);planCamera.up.set(0,0,1);const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;const pm=new T.PMREMGenerator(renderer);scene.environment=pm.fromScene(new RoomEnvironment(),.04).texture;scene.environmentIntensity=.15;
scene.add(new T.HemisphereLight(0xb7c3c3,0x3a2d1d,.65));const lights=[];for(const [p,power,color]of [[[0,2,-2.6],10,0xffedce],[[1.5,2.9,.3],8,0xd0d9dc],[[-2,2,0],5,0xe0d4bd]]){const l=new T.PointLight(color,power,12,1.5);l.position.set(...p);scene.add(l);lights.push(l)}
const target=new T.WebGLRenderTarget(innerWidth,innerHeight,{samples:4,type:T.HalfFloatType});const composer=new EffectComposer(renderer,target);composer.addPass(new RenderPass(scene,camera));const ao=new SSAOPass(scene,camera,innerWidth,innerHeight);ao.kernelRadius=.25;ao.minDistance=.001;ao.maxDistance=.10;composer.addPass(ao);composer.addPass(new OutputPass());
const topLight=new T.DirectionalLight(0xf5ead4,2.5);topLight.position.set(-2,8,-2);scene.add(topLight);topLight.visible=false;
let model,section;const poses={rightRoots:[[0,1.75,.1],[-1.7,2.85,1.2],true],wallReview:[[-.8,1.45,-2.15],[3.5,1.5,-1],true],northwest:[[1.2,1.6,0],[3,1.4,2.5],true],southwest:[[.8,1.5,-.5],[3,1.3,-3],true],southeast:[[0,1.6,-.5],[-2.8,1.3,-3],true],inside:[[0,1.65,-2.45],[0,1.65,1.3],true],west:[[-.9,1.7,-1.2],[3.7,1.5,0],true],ceilingDetail:[[0,1.5,-.2],[.8,3.3,1.5],true],floorDetail:[[1.8,1.5,-1.8],[2,.2,1.6],true],top:[[0,10,-.75],[0,0,-.75],false],overview:[[8.9,8,-10.8],[0,1.1,0],false]};
function pose(name){const [p,t,roof]=poses[name];camera=name==='top'?planCamera:perspectiveCamera;composer.passes[0].camera=camera;ao.camera=camera;controls.object=camera;topLight.visible=!roof;ao.enabled=roof;camera.position.set(...p);controls.target.set(...t);if(model){model.getObjectByName('ceiling').visible=roof;model.getObjectByName('shell').material.clippingPlanes=roof?[]:[new T.Plane(new T.Vector3(0,-1,0),1.65)];model.getObjectByName('rock').material.clippingPlanes=model.getObjectByName('shell').material.clippingPlanes;if(section)section.visible=!roof;const tips=model.getObjectByName('pendants');if(tips)tips.visible=roof;}controls.update();composer.render()}for(const name of Object.keys(poses))document.getElementById(name).onclick=()=>pose(name);document.getElementById('roof').onclick=()=>{const m=model?.getObjectByName('ceiling');if(m){m.visible=!m.visible;model.getObjectByName('shell').material.clippingPlanes=m.visible?[]:[new T.Plane(new T.Vector3(0,-1,0),1.65)];model.getObjectByName('rock').material.clippingPlanes=model.getObjectByName('shell').material.clippingPlanes;section.visible=!m.visible;const tips=model.getObjectByName('pendants');if(tips)tips.visible=m.visible}};document.getElementById('reference').onclick=()=>document.getElementById('ref').style.display='block';document.getElementById('ref').onclick=e=>e.target.style.display='none';
try{const gltf=await new GLTFLoader().loadAsync('/models/corner-left-round-cave.glb?v=28b');model=gltf.scene;model.scale.x=-1;section=makeCutawayCap(gltf.scene.children.find(o=>o.userData.doorOffsets)?.userData.doorOffsets);model.add(section);scene.add(model);model.traverse(o=>{if(o.isMesh){o.material.side=T.DoubleSide;o.material.envMapIntensity=.2}});pose(new URLSearchParams(location.search).get('view')==='wall'?'wallReview':'inside');const info=await(await fetch('/models/model-info.json')).json();document.getElementById('status').textContent=`模型 R28 · 南门偏移${(info.doorOffsets.south??0)*.5}m / 西门偏移${(info.doorOffsets.west??0)*.5}m · ${info.triangles.toLocaleString()} 三角形 · ${(info.bytes/1048576).toFixed(1)} MiB · 拖动旋转 / 滚轮缩放`;window.review={scene,model,camera,renderer,controls,pose,info};}catch(e){document.getElementById('status').textContent='加载失败：'+e.message;console.error(e)}
renderer.setAnimationLoop(()=>{controls.update();composer.render()});addEventListener('resize',()=>{renderer.setSize(innerWidth,innerHeight);perspectiveCamera.aspect=innerWidth/innerHeight;perspectiveCamera.updateProjectionMatrix();planCamera.left=-5.2*innerWidth/innerHeight;planCamera.right=5.2*innerWidth/innerHeight;planCamera.updateProjectionMatrix();composer.setSize(innerWidth,innerHeight)});
